### ISSUE TITLE
GridTraveler.java line 28

### ISSUE THREAD

**Issue by lgmarcelo** [LuizGuerra/Dynamic-Programming#3]
Can I ask how was line 28 created? I am a beginner in java and that line was the missing piece for my code to run.

**Comment by LuizGuerra** [comment]
Yes of course. To understand what the line actually does, I have to give a brief explanation of what I'm trying to accomplish here:

- The problem is to travel a grid, with the only possible ways to move are right and down.  Being dynamic programming, we need to save every point we calculate in a dictionary (called _memo_ here);
- Since the problem is mirrored from its diagonal (top left to bottom right, result of the only 2 possible movements), there is no point in saving position (X, Y) and (Y, X), because they will have the same value.

The following line was created to make sure the _key_ in the _memo_ dictionary will accomplish the last point (mirrored positions). We are using the fact that one of the values can be bigger than the other to make sure the keys won't repeat themselves.
`String key = m > n ? n+"-"+m : m+"-"+n;`

So, the key String is pretty much `if x > y then "x-y" otherwise "y-x".`
Exemplifying with values: `if 2 > 4 then "2-4" otherwise "4-2".` In this case, we will use the otherwise statement value "4-2".
